#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = true
    relativenumber = false

    bootstrap_before = "config#before"
    bootstrap_after = "config#after"

    # enable_vimfiler_gitstatus = true
    sidebar_direction = 'left'

    # colorscheme = "zenburn"

    filemanager = "nerdtree"

[[layers]]
name = 'autocomplete'
auto-completion-delay = 10
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'bottom'
default_height = 30

[[layers]]
    name = 'tools'

[[layers]]
    name = "fzf"

[[layers]]
    name = "git"

[[layers]]
    name = "format"

[[layers]]
    name = "lang#python"

[[layers]]
    name = "lang#rust"

[[layers]]
    name = "lang#c"

[[layers]]
    name = "lang#javascript"

[[layers]]
    name = "lsp"
    filetypes = [
    "rust",
    "c",
    "cpp"
    ]
    [layers.override_cmd]
        rust = ["rustup", "run", "stable", "rls"]
        c = ["clangd"]

[[layers]]
    name = "lang#ocaml"

[[layers]]
    name = "tags"

[[custom_plugins]]
    name = "jnurmine/Zenburn"

[[custom_plugins]]
    name = "ryanoasis/vim-devicons"

[[custom_plugins]]
    name = 'ctrlpvim/ctrlp.vim'

[[custom_plugins]]
    name = 'RRethy/vim-illuminate'

[[custom_plugins]]
    name = 't9md/vim-macvim-transparency'

[[custom_plugins]]
    name = 'jaxbot/semantic-highlight.vim'

[[custom_plugins]]
    name = 'hylang/vim-hy'

[[custom_plugins]]
    name = 'codeindulgence/vim-tig'

[[custom_plugins]]
    name = 'brooth/far.vim'

[[custom_plugins]]
    name = 'iberianpig/tig-explorer.vim'

[[custom_plugins]]
    name = 'tmsvg/pear-tree'

[[custom_plugins]]
    name = 'ocaml/vim-ocaml'
