"can replace whitespace with other character
set list
set listchars=tab:>-,trail:>
"set listchars=eol:$,tab:>-,trail:~,extends:>,precedes:<

if has("gui_macvim")
    source ~/.vimrc_macvim
else
    source ~/.vimrc_shell
endif
